#!/bin/bash

# دالة للحصول على رابط تحميل ZIP
_get_ziplink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "l-s-I-I" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2wtcy1JLUkvWmVsZV92cHMvYXJjaGl2ZS9tYWluLnppcA==" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/main.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL2wtcy1JLUkvWmVsZV92cHMvYXJjaGl2ZS9tYWluLnppcA==" | base64 -d
    fi
}

# دالة للحصول على رابط المستودع
_get_repolink () {
    local regex
    local rlink
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "l-s-I-I" ]]
    then
        rlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL2wtcy1JLUkvWmVsZV92cHMuZ2l0" | base64 -d`
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        rlink=`echo "${UPSTREAM_REPO}"`
    else
        rlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL2wtcy1JLUkvWmVsZV92cHMuZ2l0" | base64 -d`
    fi
    echo "$rlink"
}

# دالة لتشغيل كود بايثون
_run_python_code() {
    python3${pVer%.*} -c "$1"
}

# دالة لتنفيذ عملية Git للمستودع الرسمي
_run_zedpack_git() {
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO = "https://github.com/l-s-I-I/Zele_vps"
ACTIVE_BRANCH_NAME = "main"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

# دالة لتنفيذ عملية Git للمستودع المحدد
_run_zed_git() {
    local repolink=$(_get_repolink)
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO="'$repolink'"
ACTIVE_BRANCH_NAME = "'$UPSTREAM_REPO_BRANCH'" or "main"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

# دالة لإعداد وتشغيل البوت
_set_bot () {
    local zippath
    zippath="main.zip"
    echo "⌭ جاري تنزيل اكواد السورس ⌭"
    wget -q $(_get_ziplink) -O "$zippath"
    echo "⌭ تفريغ البيانات ⌭"
    ZEDPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "⌭ تـم التفريـغ ⌭"
    echo "⌭ يتم التنظيف ⌭"
    rm -rf "$zippath"
    sleep 5
    _run_zedpack_git
    cd $ZEDPATH
    _run_zed_git
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    chmod -R 755 bin
    echo "⌭ جـاري بـدء تنصيـب كرار ⌭"
    echo "

    "
    python3 -m zlzl
}

# تشغيل الدالة الرئيسية
_set_bot
